spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: "012345"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
